# Generated by Django 3.1 on 2020-09-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200901_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskArticle',
        ),
    ]
